javelus:
  image: docker.iwanna.xyz:5000/javelus
  command: /bin/bash -c "cd /root/6.0.41/bin && source setjavelus.sh && service mysql start && sh catalina.sh run"
  network: nap
  port: 8080
  environment:
    - JAVELUS_JAVA_HOME=/home/javelus/javelus/jdk1.6.0_45/
    - JAVELUS=/home/javelus/javelus/hotspot/build/linux/linux_i486_compiler2/fastdebug/hotspot
